# Generated by Django 5.0 on 2024-01-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('paterson', models.CharField(blank=True, max_length=250, null=True)),
                ('drc', models.CharField(blank=True, max_length=250, null=True)),
                ('salaireBase', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=70, null=True)),
                ('matricule', models.CharField(max_length=70)),
                ('nom_postnom', models.CharField(max_length=70)),
                ('adresse', models.CharField(blank=True, max_length=170, null=True)),
                ('birthday', models.DateField()),
                ('engagement', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=170, null=True)),
                ('photo', models.ImageField(blank=True, default='photo/default.png', null=True, upload_to='photo/')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Employe',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='xx', max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=170, null=True)),
                ('email', models.CharField(blank=True, max_length=170, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('duree', models.IntegerField()),
                ('matricule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hr.employe')),
            ],
            options={
                'db_table': 'conge',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_postnom', models.CharField(max_length=70)),
                ('statut', models.CharField(choices=[('En', 'Enfant'), ('EP', 'Epoux(se)'), ('PA', 'Père'), ('MA', 'Mère'), ('PE', 'Beau Père'), ('ME', 'Belle Mère')], max_length=2, verbose_name='statut')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('birthday', models.DateField(default='01/01/2000')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.employe')),
            ],
            options={
                'db_table': 'famille',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.categorie')),
            ],
            options={
                'db_table': 'fonction',
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hr.fonction'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.departement')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='fonction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.service'),
        ),
        migrations.AddField(
            model_name='departement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.site'),
        ),
    ]
